apiVersion: v1
kind: Service
metadata:
  name: account-management-http
spec:
  ports:
    - name: graphql-port
      port: 8080
      targetPort: 8080
    - name: http-port
      port: 8081
      targetPort: 8081
    - name: sharding-port
      port: 54321
      targetPort: 54321
  type: NodePort
  selector:
    app: account-management-http
