apiVersion: v1
kind: Service
metadata:
  name: shard-manager
spec:
  ports:
    - name: graphql-port
      port: 8080
      targetPort: 8080
    - name: sharding-port
      port: 54321
      targetPort: 54321
  selector:
    app: shard-manager
