version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  
  shard-manager:
    container_name: shard-manager
    image: rbraley/shard-manager

  account-management-http:
    container_name: account-management-http
    image: rbraley/account-management-http
